apiVersion: apps/v1
kind: Deployment
metadata:
  name: framemotiondetector-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: framemotiondetector-app
  template:
    metadata:
      labels:
        app: framemotiondetector-app
    spec:
      containers:
      - name: framemotiondetector
        image: registry_path/cam_series/framemotiondetector:latest
        ports:
          - containerPort: 17
        env:
          - name: CONFIG_PATH
            value: "/app/config.json"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"