FROM python:3.9-slim

WORKDIR /app

COPY . /app

# Dependencies for opencv-python-headless
RUN apt-get update && apt-get install -y \
    curl \
    libgl1-mesa-glx \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install kafka-python opencv-python-headless==4.10.0.82 numpy==1.26.4

CMD ["python", "FrameCapturer.py"]